name: Build, lint and dockerize

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: make build
      - name: Lint
        run: make lint
      - name: Docker build
        run: docker build -t latest .
